name: Continuous Integration

on:
  - push

jobs:
  CI-Job:
    runs-on:
      - codebuild-terraform-module-demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup tfLint
        uses: terraform-linters/setup-tflint@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Lint the terraform modules
        run: make init lint
