name: Continuous Integration

on: [push]

jobs:
  CI-Job:
    runs-on:
      - codebuild-terraform-module-demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - run: make lint

      - run: echo "Hello World!"
 
 
 
  NodeJs-Demo-Job:
    runs-on:
      - codebuild-terraform-module-demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node --version
      - run: ls -lsa
      - run: echo "Completed"