name: Generate terraform docs

on:
  - pull_request

jobs:
  docs:
    runs-on: codebuild-luke-github-demo-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: .terraform-docs.yml
          find-dir: modules/
          recursive: true
          git-push: true
          git-commit-message: Updating module documentation
